language: python
python:
  - "3.7-dev"

services:
  - postgresql

env:
  - DEBUG=True
  - DATABASE_URL=postgres://travis@127.0.0.1:5432/travis_ci_db
  global:
    - DJANGO_SETTINGS_MODULE="conf.settings.test_ci"

install:
  - pip install -r travis_requirements.txt
  - pip install codecov

before_script:
  - psql -c "CREATE DATABASE travis_ci_db;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic

script:
  - coverage run manage.py test

after_success:
  - codecov